before_script:
- set GRADLE_USER_HOME=$(pwd)/.gradle
# - npm install -g yarn

stages:
  - buildFrontEnd
  - sonarqube
  - build
  - dockerComposeDeployment



buildFrontEnd:
    stage: buildFrontEnd
    tags: 
        - front-end
    script:
        - cd reactFrontEnd
        - echo "Build stage started"
        - npm install
        - npm run build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build

sonarqube:
 stage: sonarqube
 tags: 
   - back-end
 script:
   - cd restAPI
   - ./gradlew sonarqube -PsonarPassword=1207

build:
  stage: build
  tags: 
    - back-end
  script:
    - cd restAPI
    - ./gradlew clean build
    - echo "Build script over"
  artifacts:
    paths:
      - build/libs/*.jar


dockerComposeDeployment:
  stage: dockerComposeDeployment
  tags: 
    - front-end
  script:
    - dir
    - echo "Deploy stage started"
    - docker-compose up -d 
    - echo "Deploy successful"


after_script:
  - echo "This is form the shell runner. After Script"

