stages:
    - buildFrontEnd
build:
    stage: buildFrontEnd
    tags: 
        - front-end
    script:
        - cd reactFrontEnd
        - echo "Build stage started"
        - yarn install
        - yarn build 
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build

